"""analyze columns added to videos table

Revision ID: 0ae6a6baab62
Revises: 52cebd7f5cba
Create Date: 2026-08-30 13:10:56.860102

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ae6a6baab62'
down_revision: Union[str, Sequence[str], None] = '52cebd7f5cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('is_analyzed', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('clickbait_score', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('overall_sentiment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'overall_sentiment')
    op.drop_column('videos', 'clickbait_score')
    op.drop_column('videos', 'is_analyzed')
    # ### end Alembic commands ###
