"""created_at column added to videos table

Revision ID: 52cebd7f5cba
Revises: b6e0cb4c554b
Create Date: 2026-08-30 12:41:30.350283

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '52cebd7f5cba'
down_revision: Union[str, Sequence[str], None] = 'b6e0cb4c554b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'created_at')
    # ### end Alembic commands ###
